version: '2'

services:
  oai-nr-ue:
    image: rdefosseoai/oai-nr-ue:develop
    privileged: true
    network_mode: "host"
    container_name: demo-oai-nr-ue
    entrypoint: /usr/bin/env
    command: sh -c "{ ./bin/uhd_images_downloader.py && exec /opt/oai-nr-ue/bin/nr-uesoftmodem.Rel15 -O /app/ue.sa.conf -E --sa -r 106 --numerology 1 --band 66 -C 2169080000 --CO -400000000 --ue-rxgain 120 --ue-txgain 0 --ue-max-power 0 --ue-scan-carrier --nokrnmod; } 2>&1 | tee /opt/oai-nr-ue/logs.txt"
    volumes: # Mounted from host
      - ./logs.txt:/opt/oai-lte-ue/logs.txt
      - ./ue.sa.conf:/app/ue.sa.conf

